### ISSUE TITLE
`fsck` fails: 'HTTPRemoteIO' object has no attribute 'in_archive') failed

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6354]
This is a ria/ora remote configured with `type=external url=ria+http://enki.ds.inm7.de`.

```
% git annex fsck --fast -f inm7-storage
fsck dataset_description.json [INFO] Fetching 'http://enki.ds.inm7.de/ria-layout-version' 
[INFO] Fetching 'http://enki.ds.inm7.de/6e6/61818-b617-11ea-ae2d-b4969157768c/ria-layout-version' 
('HTTPRemoteIO' object has no attribute 'in_archive') failed
fsck desc-aparcaseg_dseg.tsv ('HTTPRemoteIO' object has no attribute 'in_archive') failed
...
```

Whether or not `--fast` is used is irrelevant.

Source of the error is

```
[2022-01-19 11:17:54.833641188] /home/mih/venvs/datalad/bin/git-annex-remote-ora[1] --> CHECKPRESENT-UNKNOWN MD5E-s49926--3c24235cafe15cbf27fe67b55bbe7815.tsv 'HTTPRemoteIO' object has no attribute 'in_archive'
('HTTPRemoteIO' object has no attribute 'in_archive') failed
```

Also happening with 0.15.3

And the reason is that `HTTPRemoteIO` is used as an `IOBase` instance -- which it is simply not.

**Comment by bpoldrack** [comment]
On it. Apparently I broke it in a4b87f0c58047c9337e0cd1604f2b3eaeaae99a7

**Comment by bpoldrack** [comment]
Only thing not yet clear to me: Why did the test not catch it?
