### ISSUE TITLE
`push` not working with snapshot of 0.13

### ISSUE THREAD

**Issue by loj** [datalad/datalad#4648]
#### What is the problem?

I was trying out a snapshot of datalad 0.13 that @mih deployed on a remote server and ran into problems with `datalad push`.

@mih mentioned: "This likely means we need to backport tqdm."

#### What steps will reproduce the problem?

```
loj@bulk1 in ~
❱ datalad create mydataset
[INFO   ] Creating a new annex repo at /home/loj/mydataset 
create(ok): /home/loj/mydataset (dataset)

❱ cd mydataset

❱ touch file1.txt

❱ datalad save -m "create file"
add(ok): file1.txt (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

❱ datalad siblings add --name jugit --url https://jugit.fz-juelich.de/loj/test         
[INFO   ] Could not enable annex remote jugit. This is expected if jugit is a pure Git remote, or happens if it is not accessible. 
[WARNING] Could not detect whether jugit carries an annex. If jugit is a pure Git remote, this is expected. Remote was marked by annex as annex-ignore. Edit .git/config to reset if you think that was done by mistake due to absent connection etc 
.: jugit(-) [https://jugit.fz-juelich.de/loj/test (git)]

❱ datalad push --to jugit
Push:   0%|                                                              | 0.00/4.00 [00:00<?, ? Steps/s]
[ERROR  ] 'tqdm' object has no attribute 'reset' [progressbars.py:update:267] (AttributeError) 
```
#### What version of DataLad are you using?

<details><summary>datalad wtf</summary>
<p>

```
❱ datalad wtf                                                                                        1 !
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## datalad 
  - full_version: 0.13.0rc2
  - version: 0.13.0rc2
## dataset 
  - id: 0880e76c-b46e-11ea-9c57-a0369f287950
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/loj/mydataset
  - repo: AnnexRepo
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.44.0
  - cmd:7z: 16.02
  - cmd:annex: 7.20190819+git2-g908476a9b-1~ndall+1
  - cmd:bundled-git: 2.20.1
  - cmd:git: 2.20.1
  - cmd:system-git: 2.24.0
  - cmd:system-ssh: 7.9p1
  - exifread: 2.1.2
  - git: 3.0.5
  - gitdb: 2.0.6
  - humanize: 0.5.1
  - iso8601: 0.1.11
  - keyring: 17.1.1
  - keyrings.alt: 3.1.1
  - msgpack: 0.5.6
  - mutagen: 1.40.0
  - requests: 2.21.0
  - tqdm: 4.28.1
  - wrapt: 1.10.11
## environment 
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - PATH: /home/loj/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games
## extensions 
  - inm7: 
    - description: INM7 utilities
    - entrypoints: 
    - load_error: None
    - module: inm7_datalad
    - version: 0.5+10.g5f93ec5
  - ria: 
    - description: Helper for the remote indexed archive (RIA) special remote
    - entrypoints: 
      - ria_remote.export_archive.ExportArchive: 
        - class: ExportArchive
        - load_error: None
        - module: ria_remote.export_archive
        - names: 
          - ria-export-archive
          - ria_export_archive
    - load_error: None
    - module: ria_remote
    - version: 0.6+6.ge755961
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 5
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20190819+git2-g908476a9b-1~ndall+1
## location 
  - path: /home/loj/mydataset
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: None
    - module: datalad.metadata.extractors.xmp
    - version: None
## python 
  - implementation: CPython
  - version: 3.7.3
## system 
  - distribution: debian/10.4
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 275
  - name: Linux
  - release: 4.19.0-8-amd64
  - type: posix
  - version: #1 SMP Debian 4.19.98-1 (2020-01-26)
```
</p>
</details>

**Comment by mih** [comment]
Thanks @loj

The code that calls this function is relatively recent. We need to check which version it is coming from, adjust the deps, or figure out whether we can get away without a dependency update somehow.

**Comment by kyleam** [comment]
It looks like tqdm added `.reset()` in v4.32.0 (c7015f4, 2019-05-10).

That method is five lines of code and didn't involve changes elsewhere, so I think it'd be a reasonable approach to add a fall back kludge with the same logic on our side.
