### ISSUE TITLE
`download-url -d <path>` fails

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3468]
Demo:

```
datalad --dbg download-url -d raw -O raw/acq2/events.tsv https://github.com/datalad/example-dicom-functional/raw/master/events.tsv
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/bin/datalad", line 8, in <module>
    main()
  File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 500, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/base.py", line 645, in call_from_parser
    ret = list(ret)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 520, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/interface/download_url.py", line 91, in __call__
    pwd, rel_pwd = get_dataset_pwds(dataset)
  File "/home/mih/hacking/datalad/git/datalad/utils.py", line 1804, in get_dataset_pwds
    pwd = dataset.path
AttributeError: 'str' object has no attribute 'path'

> /home/mih/hacking/datalad/git/datalad/utils.py(1804)get_dataset_pwds()
-> pwd = dataset.path
```

I does not expect the Spanish Inquisition.

**Comment by kyleam** [comment]
Like gh-3463, this was introduced by fc25ac55d (BF: Do not duplicate/auto-convert dataset args to instances, 2019-05-20).  I'll look into updating download-url.

After the dataset-handling is fixed, your above snippet will run into an issue with the path handling.  download-url follows the old "if dataset given, paths are relative to it" design, so it'd expect `-O acq2/events.tsv` instead of `-O raw/acq2/events.tsv`.

**Comment by mih** [comment]
@kyleam I agree, there will be (almost should be) many more. Gotta crunch through them one by one.
